[project]
name = "bilibili-my-favorite"
version = "0.1.0"
description = "缓存并检测我收藏夹内的"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.18",
    "bilibili-api-python>=17.1.4",
    "curl-cffi>=0.11.1",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "rich>=14.0.0",
]
